from __future__ import annotations

SECTIONS = [
    {
        "title": "Revenue & Growth",
        "questions": [
            {
                "field_id": "current_arr",
                "label": "Current ARR",
                "type": "currency",
                "required": True,
                "min": 0.0,
                "default": 2_400_000.0,
                "step": 25_000.0,
                "unit": "US dollars ($)",
                "context_text": "Annualized recurring subscription revenue only; exclude one-time services and hardware.",
                "help_text": "Use current annualized recurring subscription revenue. Exclude one-time services and hardware revenue.",
            },
            {
                "field_id": "prior_arr",
                "label": "ARR 12 months ago",
                "type": "currency",
                "required": True,
                "min": 0.0,
                "default": 2_000_000.0,
                "step": 25_000.0,
                "unit": "US dollars ($)",
                "context_text": "Used to calculate trailing ARR growth over the last year.",
                "help_text": "Used to calculate trailing ARR growth.",
            },
            {
                "field_id": "forward_arr",
                "label": "Expected ARR in 12 months",
                "type": "currency",
                "required": True,
                "min": 0.0,
                "default": 2_880_000.0,
                "step": 25_000.0,
                "unit": "US dollars ($)",
                "context_text": "Your best estimate of ARR one year from today; used as a forward-looking confidence overlay.",
                "help_text": "Used as a forward-looking confidence overlay.",
            },
            {
                "field_id": "recurring_revenue_pct",
                "label": "Recurring subscription revenue",
                "type": "percentage",
                "required": True,
                "min": 0.0,
                "max": 100.0,
                "default": 90.0,
                "step": 1.0,
                "unit": "percentage of total revenue (%)",
                "context_text": "Share of revenue that is true recurring software subscription revenue.",
                "help_text": "Include contracted recurring software subscriptions. Exclude one-time fees and most services.",
            },
            {
                "field_id": "services_revenue_pct",
                "label": "Services and implementation revenue",
                "type": "percentage",
                "required": True,
                "min": 0.0,
                "max": 100.0,
                "default": 10.0,
                "step": 1.0,
                "unit": "percentage of total revenue (%)",
                "context_text": "Share of revenue coming from implementation, consulting, or other non-recurring services.",
                "help_text": "Higher services mix generally reduces SaaS multiples.",
            },
        ],
    },
    {
        "title": "Retention & Customer Quality",
        "questions": [
            {
                "field_id": "nrr_pct",
                "label": "Net Revenue Retention (NRR)",
                "type": "percentage",
                "required": True,
                "min": 0.0,
                "max": 300.0,
                "default": 100.0,
                "step": 1.0,
                "unit": "percentage (%)",
                "context_text": "Revenue retained from the starting customer cohort after expansion, downgrades, and churn.",
                "help_text": "Revenue retained from the starting customer cohort after expansion, downgrades, and churn.",
            },
            {
                "field_id": "grr_pct",
                "label": "Gross Revenue Retention (GRR)",
                "type": "percentage",
                "required": True,
                "min": 0.0,
                "max": 100.0,
                "default": 90.0,
                "step": 1.0,
                "unit": "percentage (%)",
                "context_text": "Revenue retained before any expansion revenue is included.",
                "help_text": "Revenue retained before expansion.",
            },
            {
                "field_id": "logo_churn_pct",
                "label": "Annual logo churn",
                "type": "percentage",
                "required": True,
                "min": 0.0,
                "max": 100.0,
                "default": 10.0,
                "step": 1.0,
                "unit": "percentage of customers (%)",
                "context_text": "Percent of customers lost over the last 12 months.",
                "help_text": "Percent of customers lost over the last 12 months.",
            },
            {
                "field_id": "acv",
                "label": "Average contract value (ACV)",
                "type": "currency",
                "required": True,
                "min": 0.0,
                "default": 5_000.0,
                "step": 500.0,
                "unit": "US dollars ($)",
                "context_text": "Average annual contract value or annual revenue per customer account.",
                "help_text": "Use your best estimate if you do not track ACV formally.",
            },
            {
                "field_id": "largest_customer_arr_pct",
                "label": "ARR from the single largest customer",
                "type": "percentage",
                "required": True,
                "min": 0.0,
                "max": 100.0,
                "default": 10.0,
                "step": 1.0,
                "unit": "percentage of ARR (%)",
                "context_text": "High customer concentration increases buyer risk.",
                "help_text": "High concentration increases buyer risk.",
            },
        ],
    },
    {
        "title": "Profitability & Efficiency",
        "questions": [
            {
                "field_id": "top5_customer_arr_pct",
                "label": "ARR from the top 5 customers",
                "type": "percentage",
                "required": True,
                "min": 0.0,
                "max": 100.0,
                "default": 20.0,
                "step": 1.0,
                "unit": "percentage of ARR (%)",
                "context_text": "Combined ARR concentration across your five largest customers.",
                "help_text": "Used to assess broader concentration risk.",
            },
            {
                "field_id": "gross_margin_pct",
                "label": "Gross margin",
                "type": "percentage",
                "required": True,
                "min": -100.0,
                "max": 100.0,
                "default": 75.0,
                "step": 1.0,
                "unit": "percentage (%)",
                "context_text": "Calculated as (revenue minus cost of revenue) divided by revenue.",
                "help_text": "(Revenue - cost of revenue) / revenue.",
            },
            {
                "field_id": "ebitda_margin_pct",
                "label": "EBITDA margin",
                "type": "percentage",
                "required": True,
                "min": -100.0,
                "max": 100.0,
                "default": 0.0,
                "step": 1.0,
                "unit": "percentage (%)",
                "context_text": "Use EBITDA margin if available; otherwise use operating margin as a proxy.",
                "help_text": "Use EBITDA margin if available. Otherwise use operating margin.",
            },
            {
                "field_id": "cac_payback_months",
                "label": "CAC payback period",
                "type": "number",
                "required": True,
                "min": 0.0,
                "max": 120.0,
                "default": 12.0,
                "step": 1.0,
                "unit": "months",
                "context_text": "Months required to recover customer acquisition cost from gross profit.",
                "help_text": "Number of months required to recover customer acquisition cost from gross profit.",
            },
            {
                "field_id": "sales_cycle_days",
                "label": "Average sales cycle",
                "type": "number",
                "required": True,
                "min": 0.0,
                "max": 730.0,
                "default": 45.0,
                "step": 1.0,
                "unit": "days",
                "context_text": "Approximate days from qualified opportunity to closed-won.",
                "help_text": "Approximate average number of days from qualified opportunity to close.",
            },
        ],
    },
    {
        "title": "Risk, Transferability & Balance Sheet",
        "questions": [
            {
                "field_id": "billing_profile",
                "label": "Typical billing profile",
                "type": "radio",
                "required": True,
                "options": [
                    "mostly_monthly",
                    "mixed_monthly_annual",
                    "mostly_annual_upfront",
                    "multi_year_common",
                ],
                "default": "mostly_monthly",
                "context_text": "Billing terms affect revenue quality, visibility, and cash flow.",
                "help_text": "Better billing terms improve revenue quality and cash flow.",
                "option_labels": {
                    "mostly_monthly": "Mostly monthly",
                    "mixed_monthly_annual": "Mixed monthly and annual",
                    "mostly_annual_upfront": "Mostly annual upfront",
                    "multi_year_common": "Multi-year contracts are common",
                },
            },
            {
                "field_id": "founder_dependence",
                "label": "Founder dependence",
                "type": "radio",
                "required": True,
                "options": [
                    "very_dependent",
                    "somewhat_dependent",
                    "mostly_independent",
                    "fully_management_led",
                ],
                "default": "mostly_independent",
                "context_text": "How much the business depends on the founder for sales, product, or key relationships.",
                "option_labels": {
                    "very_dependent": "Very dependent",
                    "somewhat_dependent": "Somewhat dependent",
                    "mostly_independent": "Mostly independent",
                    "fully_management_led": "Fully management-led",
                },
            },
            {
                "field_id": "product_differentiation",
                "label": "Product differentiation",
                "type": "radio",
                "required": True,
                "options": [
                    "weak_or_commoditized",
                    "somewhat_differentiated",
                    "clearly_differentiated",
                    "strong_moat_or_category_leader",
                ],
                "default": "somewhat_differentiated",
                "context_text": "How clearly the product stands apart from alternatives in the market.",
                "option_labels": {
                    "weak_or_commoditized": "Weak or commoditized",
                    "somewhat_differentiated": "Somewhat differentiated",
                    "clearly_differentiated": "Clearly differentiated",
                    "strong_moat_or_category_leader": "Strong moat or category leader",
                },
            },
            {
                "field_id": "reporting_quality",
                "label": "Reporting quality",
                "type": "radio",
                "required": True,
                "options": [
                    "basic_or_messy",
                    "decent_but_incomplete",
                    "strong_and_board_ready",
                    "very_strong_and_diligence_ready",
                ],
                "default": "decent_but_incomplete",
                "context_text": "Strength and reliability of your financial reporting and SaaS KPI tracking.",
                "option_labels": {
                    "basic_or_messy": "Basic or messy",
                    "decent_but_incomplete": "Decent but incomplete",
                    "strong_and_board_ready": "Strong and board-ready",
                    "very_strong_and_diligence_ready": "Very strong and diligence-ready",
                },
            },
            {
                "field_id": "net_cash",
                "label": "Net cash or net debt",
                "type": "currency_signed",
                "required": True,
                "default": 0.0,
                "step": 25_000.0,
                "unit": "US dollars ($)",
                "context_text": "Enter positive for net cash and negative for net debt.",
                "help_text": "Enter positive for net cash and negative for net debt.",
            },
        ],
    },
]


def all_questions() -> list[dict]:
    return [question for section in SECTIONS for question in section["questions"]]
